name: Build and deploy functions

on:
  push:
    branches: [main]
    paths: ["functions/**"]

concurrency: ${{ github.ref }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          GOOGLE_APPLICATION_CREDENTIALS="$(mktemp)"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV
          echo "GCLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: |
          pnpm install --frozen-lockfile
          pnpm --filter functions run build
          pnpm exec firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          pnpm exec firebase deploy --only functions
