name: Build and deploy functions

on:
  push:
    branches: [main]
    paths: ["functions/**"]

concurrency: ${{ github.ref }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          GOOGLE_APPLICATION_CREDENTIALS="$(mktemp)"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV
          echo "GCLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          cache-dependency-path: yarn.lock
          node-version: 16
      - run: |
          yarn install --frozen-lockfile
          yarn workspace functions run build
          yarn exec -- firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          yarn exec -- firebase deploy --only functions
