name: Build pull request

on: pull_request

jobs:
  build_bot:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bot
    steps:
      - uses: actions/checkout@v3
      - run: pip install pycodestyle
      - run: pycodestyle .
  build_site:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run check
      - run: npm run lint
      - run: npm run build
