name: Build and deploy site

on:
  push:
    branches: [main]
    paths: ["site/**"]
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Paris"
      LANG: "fr_FR.UTF-8"
    steps:
      - uses: actions/checkout@v3
      - run: |
          GOOGLE_APPLICATION_CREDENTIALS="$(mktemp)"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV
          echo "GCLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: |
            site/package-lock.json
      - run: npm ci && npm run build
        working-directory: site
      - run: |
          npx -q firebase-tools use ${{ secrets.FIREBASE_PROJECT_ID }}
          npx -q firebase-tools target:apply hosting site ${{ secrets.FIREBASE_SITE_ID }}
          npx -q firebase-tools deploy --only hosting:site
