name: Build and deploy site

on:
  push:
    branches: [main]
    paths: ["site/**"]
  workflow_dispatch:

concurrency: ${{ github.ref }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Paris"
      LANG: "fr_FR.UTF-8"
    steps:
      - uses: actions/checkout@v3
      # TODO: Find a better way to depend on FIRESTORE_EMULATOR_HOST optional env variable
      - run: |
          GOOGLE_APPLICATION_CREDENTIALS="$(mktemp)"
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "$GOOGLE_APPLICATION_CREDENTIALS"
          echo "FIRESTORE_EMULATOR_HOST=" >> $GITHUB_ENV
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV
          echo "GCLOUD_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: |
          pnpm install --frozen-lockfile
          pnpm --filter site build
          pnpm exec firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          pnpm exec firebase target:apply hosting site ${{ secrets.FIREBASE_SITE_ID }}
          pnpm exec firebase deploy --only hosting:site
